server:
  port: 6969

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ctguctgu/yuegou-config-server.git
  application:
    name: YUEGOU-CONFIG

#将配置中心服务端注册到Eureka注册中心中
eureka:
  client:
    service-url:
      defaultZone: http://root:821096@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
