server:
  port: 9999
spring:
  application:
    name: YUEGOU-ZUUL
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://root:821096@localhost:8761/eureka/
zuul:
  ignored-services: '*' #只能通过路由访问，不能使用服务名访问
  routes:
    plat:
      serviceId: YUEGOU-PLAT
      path: /plat/**
  prefix: /services